import type { Farm, Product } from "./types"

export const products: Product[] = [
  {
    id: "p1",
    name: "Fresh Organic Tomatoes",
    description:
      "Vine-ripened, organic tomatoes grown using sustainable practices. Perfect for salads, sandwiches, or cooking.",
    price: 4.99,
    unit: "lb",
    image: "/placeholder.svg?height=300&width=300",
    category: "Vegetables",
    farmId: "f1",
    farmName: "Green City Farm",
    distance: 1.2,
    rating: 4.8,
    harvestDate: "Today",
    availableQuantity: 25,
    growingMethod: "Organic",
  },
  {
    id: "p2",
    name: "Mixed Salad Greens",
    description: "A blend of fresh, crisp lettuce varieties harvested daily. Grown without pesticides.",
    price: 3.49,
    unit: "bunch",
    image: "/placeholder.svg?height=300&width=300",
    category: "Vegetables",
    farmId: "f2",
    farmName: "Rooftop Greens",
    distance: 0.8,
    rating: 4.7,
    harvestDate: "Today",
    availableQuantity: 15,
    growingMethod: "Hydroponic",
  },
  {
    id: "p3",
    name: "Fresh Basil",
    description: "Aromatic basil leaves, perfect for Italian dishes, pesto, or garnishing. Grown in our vertical farm.",
    price: 2.99,
    unit: "bunch",
    image: "/placeholder.svg?height=300&width=300",
    category: "Herbs",
    farmId: "f3",
    farmName: "Vertical Harvest",
    distance: 2.5,
    rating: 4.9,
    harvestDate: "Yesterday",
    availableQuantity: 20,
    growingMethod: "Vertical Farming",
  },
  {
    id: "p4",
    name: "Strawberries",
    description: "Sweet, juicy strawberries grown using organic practices. Great for snacking, desserts, or smoothies.",
    price: 5.99,
    unit: "pint",
    image: "/placeholder.svg?height=300&width=300",
    category: "Fruits",
    farmId: "f1",
    farmName: "Green City Farm",
    distance: 1.2,
    rating: 4.6,
    harvestDate: "Today",
    availableQuantity: 10,
    growingMethod: "Organic",
  },
  {
    id: "p5",
    name: "Microgreens Mix",
    description: "Nutrient-dense microgreens with intense flavors. Add to salads, sandwiches, or use as a garnish.",
    price: 6.99,
    unit: "box",
    image: "/placeholder.svg?height=300&width=300",
    category: "Microgreens",
    farmId: "f2",
    farmName: "Rooftop Greens",
    distance: 0.8,
    rating: 4.8,
    harvestDate: "Today",
    availableQuantity: 8,
    growingMethod: "Hydroponic",
  },
  {
    id: "p6",
    name: "Fresh Cucumbers",
    description: "Crisp, refreshing cucumbers grown using sustainable practices. Perfect for salads or snacking.",
    price: 2.49,
    unit: "lb",
    image: "/placeholder.svg?height=300&width=300",
    category: "Vegetables",
    farmId: "f3",
    farmName: "Vertical Harvest",
    distance: 2.5,
    rating: 4.7,
    harvestDate: "Yesterday",
    availableQuantity: 15,
    growingMethod: "Vertical Farming",
  },
  {
    id: "p7",
    name: "Bell Peppers",
    description: "Colorful, sweet bell peppers grown without pesticides. Great for cooking, salads, or stuffing.",
    price: 3.99,
    unit: "lb",
    image: "/placeholder.svg?height=300&width=300",
    category: "Vegetables",
    farmId: "f1",
    farmName: "Green City Farm",
    distance: 1.2,
    rating: 4.5,
    harvestDate: "2 days ago",
    availableQuantity: 12,
    growingMethod: "Organic",
  },
  {
    id: "p8",
    name: "Fresh Mint",
    description: "Aromatic mint leaves, perfect for teas, cocktails, or cooking. Grown hydroponically.",
    price: 2.49,
    unit: "bunch",
    image: "/placeholder.svg?height=300&width=300",
    category: "Herbs",
    farmId: "f2",
    farmName: "Rooftop Greens",
    distance: 0.8,
    rating: 4.9,
    harvestDate: "Today",
    availableQuantity: 18,
    growingMethod: "Hydroponic",
  },
]

export const farms: Farm[] = [
  {
    id: "f1",
    name: "Green City Farm",
    description: "An organic urban farm growing a variety of vegetables and fruits in the heart of the city.",
    longDescription:
      "Green City Farm was established in 2015 with a mission to bring fresh, organic produce to urban communities. We grow a wide variety of vegetables, fruits, and herbs using sustainable, organic practices that prioritize soil health and biodiversity. Our farm is located on a formerly vacant lot that has been transformed into a productive green space that serves the community.",
    location: "Downtown",
    address: "123 Main St, Anytown, USA",
    coverImage: "/placeholder.svg?height=400&width=600",
    distance: 1.2,
    rating: 4.8,
    reviewCount: 124,
    established: "2015",
    hours: "Mon-Sat: 9am-5pm",
    growingMethods:
      "We use organic growing methods that focus on building healthy soil through composting, crop rotation, and natural pest management. Our farm is certified organic and we never use synthetic pesticides or fertilizers.",
    sustainabilityPractices:
      "Our farm implements rainwater harvesting, solar power for irrigation, and composting of all organic waste. We also use cover cropping and no-till practices to build soil health and sequester carbon.",
    reviews: [
      {
        name: "Sarah Johnson",
        avatar: "/placeholder.svg?height=50&width=50",
        date: "2 weeks ago",
        rating: 5,
        comment:
          "The produce from Green City Farm is always fresh and delicious! I love knowing exactly where my food comes from and supporting local urban agriculture.",
      },
      {
        name: "Michael Chen",
        avatar: "/placeholder.svg?height=50&width=50",
        date: "1 month ago",
        rating: 4,
        comment:
          "Great quality vegetables and friendly service. I appreciate their commitment to organic growing practices.",
      },
      {
        name: "Emily Rodriguez",
        avatar: "/placeholder.svg?height=50&width=50",
        date: "2 months ago",
        rating: 5,
        comment:
          "I've been getting my produce from Green City Farm for over a year now and have never been disappointed. Their tomatoes are especially amazing!",
      },
    ],
  },
  {
    id: "f2",
    name: "Rooftop Greens",
    description: "A hydroponic rooftop farm specializing in salad greens, herbs, and microgreens.",
    longDescription:
      "Rooftop Greens was founded in 2018 to utilize unused urban rooftop space for food production. We specialize in hydroponic growing systems that use 90% less water than conventional farming while producing high-quality greens year-round. Our rooftop location reduces food miles and our produce goes from harvest to customer within hours.",
    location: "Midtown",
    address: "456 Park Ave, Anytown, USA",
    coverImage: "/placeholder.svg?height=400&width=600",
    distance: 0.8,
    rating: 4.7,
    reviewCount: 89,
    established: "2018",
    hours: "Tue-Sun: 10am-6pm",
    growingMethods:
      "We use nutrient film technique (NFT) hydroponic systems to grow our greens and herbs. This soil-less method circulates a nutrient-rich water solution through channels where plants grow, allowing for precise control of growing conditions and efficient use of resources.",
    sustainabilityPractices:
      "Our hydroponic systems use 90% less water than conventional farming. We power our farm with renewable energy and use compostable packaging for all our products. Our rooftop location also helps reduce the urban heat island effect.",
    reviews: [
      {
        name: "David Wilson",
        avatar: "/placeholder.svg?height=50&width=50",
        date: "1 week ago",
        rating: 5,
        comment:
          "The microgreens from Rooftop Greens are incredible! So flavorful and they last much longer than store-bought greens.",
      },
      {
        name: "Lisa Park",
        avatar: "/placeholder.svg?height=50&width=50",
        date: "3 weeks ago",
        rating: 4,
        comment:
          "I love their salad mix - always fresh and crisp. The hydroponic growing method seems to give the greens an extra clean taste.",
      },
      {
        name: "James Taylor",
        avatar: "/placeholder.svg?height=50&width=50",
        date: "2 months ago",
        rating: 5,
        comment:
          "Great concept and execution. The herbs are so aromatic and flavorful - nothing like what you get at the supermarket.",
      },
    ],
  },
  {
    id: "f3",
    name: "Vertical Harvest",
    description: "An innovative vertical farm using LED lighting and hydroponics to grow vegetables year-round.",
    longDescription:
      "Vertical Harvest launched in 2019 as a solution to urban food production challenges. Our vertical farming system uses stacked growing trays with LED lighting and hydroponics to produce vegetables in a controlled environment 365 days a year, regardless of weather conditions. We focus on high-quality, pesticide-free produce with minimal environmental impact.",
    location: "East Side",
    address: "789 Tech Blvd, Anytown, USA",
    coverImage: "/placeholder.svg?height=400&width=600",
    distance: 2.5,
    rating: 4.9,
    reviewCount: 76,
    established: "2019",
    hours: "Mon-Fri: 11am-7pm",
    growingMethods:
      "Our vertical farming system uses stacked growing trays with specialized LED lighting that provides the optimal light spectrum for plant growth. We use a recirculating hydroponic system that delivers nutrients directly to plant roots, eliminating the need for soil and reducing water usage by up to 95%.",
    sustainabilityPractices:
      "Our controlled environment allows us to grow without pesticides or herbicides. We use energy-efficient LED lighting and recirculate 95% of our water. Our central urban location reduces transportation emissions and our year-round production helps reduce seasonal import dependence.",
    reviews: [
      {
        name: "Rachel Kim",
        avatar: "/placeholder.svg?height=50&width=50",
        date: "3 days ago",
        rating: 5,
        comment:
          "The consistency and quality of Vertical Harvest's produce is impressive. I love that they can grow locally year-round!",
      },
      {
        name: "Thomas Brown",
        avatar: "/placeholder.svg?height=50&width=50",
        date: "2 weeks ago",
        rating: 5,
        comment:
          "Their basil is incredible - so flavorful and fresh. I also appreciate their commitment to sustainability.",
      },
      {
        name: "Sophia Martinez",
        avatar: "/placeholder.svg?height=50&width=50",
        date: "1 month ago",
        rating: 4,
        comment:
          "Great quality vegetables and I love supporting innovative urban farming. The tour of their facility was fascinating!",
      },
    ],
  },
]

